### PR TITLE
Fix repository enable commands

### LINKED ISSUE #156: katello-deploy is miss configuring repositories
From latest run:

```
Running shell command: yum-CONFIG-manager --disable "*"
sh: yum-CONFIG-manager: command not found

Running shell command: yum-CONFIG-manager --enable epel

Running shell command: subscription-manager repos --enable rhel-7-server-rpms--enable rhel-7-server-extras-rpms --enable rhel-7-server-optional-rpms
cannot parse argument: rhel-7-server-extras-rpms
```

Should be called `yum-config-manager` instead of `yum-CONFIG-manager` because:

```
# yum-CONFIG-manager
-bash: yum-CONFIG-manager: command not found
```

On the generated subscription manager command is missing a space right after `rhel-7-server-rpms` to separate the `--enable` for `rhel-7-server-extras-rpms`.

Also katello-deploy should fail if a non-zero return code is returned.

### PR DESCRIPTION
**Pull request by elyezer**
Make sure to call `yum-config-manager` instead of `yum-CONFIG-manager`.
Also fix subscription-manager call to enable rhel repositories.

Closes #156

### CODE REVIEW

File: lib/katello_deploy/repositories.rb [hunk 1]
```diff
@@ -46,10 +46,10 @@ def configure_rhel(os_version)
...
       system("yum -y  --disablerepo=\"*\" --enablerepo=rhel-#{os_version}-server-rpms install yum-utils wget")
       system('yum repolist') # TODO: necessary?
-      system('yum-CONFIG-manager --disable "*"')
-      system('yum-CONFIG-manager --enable epel')
+      system('yum-config-manager --disable "*"')
+      system('yum-config-manager --enable epel')
       system(
-        "subscription-manager repos --enable rhel-#{os_version}-server-rpms" \
+        "subscription-manager repos --enable rhel-#{os_version}-server-rpms " \
         "--enable rhel-#{os_version}-server-extras-rpms --enable rhel-#{os_version}-server-optional-rpms"
```
Comment (stbenjam) [inline lib/katello_deploy/repositories.rb]: This is going to render as `subscription-manager repos --enable rhel-#{os_version}-server-rpms--enable` with the enable attached to the previous repo name.

**Comment by omaciel** [comment]
@ehelms bump :)

File: lib/katello_deploy/repositories.rb (hunk 1 above)
Comment (elyezer) [inline lib/katello_deploy/repositories.rb]: @stbenjam even adding the space there? What I should do then? Because the idea is to avoid that rendering which is already happening. (I'm using my python skills in order to fix this, but probably in ruby it is different)

Comment (stbenjam) [inline lib/katello_deploy/repositories.rb]: D'oh, sorry, hadn't had caffeine yet.  It's right :-)

**Comment by stbenjam** [comment]
Looks good to me

File: lib/katello_deploy/repositories.rb (hunk 1 above)
Comment (elyezer) [inline lib/katello_deploy/repositories.rb]: @stbenjam thank you.

**Comment by ehelms** [comment]
ACK, thanks @elyezer
